### ISSUE TITLE
About AdiphyBot

### ISSUE THREAD

**Issue by mishojack** [llllIHARWINDERIllll/AdiphyBot#1]
Hello i dont know to start adiphybot can you help me please ?
![1](https://cloud.githubusercontent.com/assets/26385330/23859795/2e331c3c-0805-11e7-8cdd-ab4f3210bd88.png)

**Comment by llllIHARWINDERIllll** [comment]
I see you have Windows. 😄 

1. Please Hold Windows key ⊞ and press R
2. A Windows Run window will pop-up.
3. Enter CMD into that window and press Enter.

Then use the TIPS to change your directory to the unpacked bot directory.

Then start the bot using: java -jar adiphy.jar

Have a nice day and Goodluck! 👋

**Comment by mishojack** [comment]
![1](https://cloud.githubusercontent.com/assets/26385330/23866274/9af527a8-0818-11e7-98e4-4232790efed2.png)

Now what is problem??? sorry for spam.. i really need this auto :))

**Comment by llllIHARWINDERIllll** [comment]
Check if you have java installed. If not please install it 👍 

It seems like that the environment values of Java aren't set. Please look into this tutorial:
https://www.java.com/en/download/help/path.xml

👌

**Comment by mishojack** [comment]
![132](https://cloud.githubusercontent.com/assets/26385330/23901133/31d48576-08bc-11e7-9a41-4bcde5dfd44c.png)
I inastall java and what is now problem ? -.0

**Comment by tonyrayo** [comment]
My guess would be that you don't have permissions... I know this is an old/dead/closed post but here is an example of a shortcut I made in Windows 10 (should work for any version).

C:\Windows\System32\cmd.exe /k java -jar C:\Users\myusername\Desktop\AdiphyBot-master\adiphy.jar

If the java runtime is installed correctly, this should launch a command prompt (the /k flag keeps the prompt active) then tell java to launch the applet at a specified location.  The nice thing about doing it this way is that if you are running without administrative privileges, you could set the shortcut to run under someone that does or ask/request permission upon launch.
