### ISSUE TITLE
Botting

### ISSUE THREAD

**Issue by Menziess** [llllIHARWINDERIllll/AdiphyBot#3]
Is it legal? 

![capture](https://cloud.githubusercontent.com/assets/7140413/23910437/0466ad26-08da-11e7-87d2-54305f32aecb.PNG) [src](http://adiphy.com/terms_conditions/)

**Comment by llllIHARWINDERIllll** [comment]
Botting the website is fully legal but according to their TOS they can deny a payout if you bot it, therefor making it risky. They can ban your account and deny payout when their TOS is broken.
