### ISSUE TITLE
List of proxies [suggestion]

### ISSUE THREAD

**Issue by BenBaltz** [llllIHARWINDERIllll/AdiphyBot#7]
Possibly instead of using one proxy for all of the articles, use a text file and switch proxies every 50 or 100 articles? Just an idea, awesome bot.

**Comment by llllIHARWINDERIllll** [comment]
Thank you for the suggestion!

Sadly, there isnt a benefit in adding this option. Mainly as it would look suspicious. A normal user only visits a website from 1 country and mostly(if the IP is static) from 1 IP. Therefor its not an good idea to change the IP after a certain amount of articles.
