### ISSUE TITLE
Im getting this error , can you explain this ?

### ISSUE THREAD

**Issue by skyegf** [llllIHARWINDERIllll/AdiphyBot#9]
![wat is dis](https://cloud.githubusercontent.com/assets/26622035/24241087/ff862c7e-0fb3-11e7-86c9-857ddc4134ee.PNG)

**Comment by asayoyaasa** [comment]
me too, but i try to close and reopen the bot. and everything go back to normal

**Comment by llllIHARWINDERIllll** [comment]
This is due to an incompability with the Proxy used. I will update the bot within the upcoming 48 hours 👍 

Have a nice day!
